config/routes.rb
DOE::Application.routes.draw do
  root to: "home#show", via: :get

  resources :customers, only:[:create, :show, :new, :update]

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :email

  has_many :utilities  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  respond_to :html

  def index
    @customer = Customer.all
  end

  def new
    #@customer = Customer.new(:first_name, :last_name, :zipcode, :email)
  end

  def create
    @customer = sign_up(customer_params)
    sign_in(@customer)
    respond_with @customer, location: root_path  	
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def update
  end
  
  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :email)
  end

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/customers/new.html.erb
<%= form_for 'customer' do |f| %>
  <div>
  	<%= f.label "First Name" %>
    <%= f.text_field "first_name" %>
  </div>
  <div>
    <%= f.label "Last Name" %>
    <%= f.text_field "last_name" %>
  </div>
  <div>
  	<%= f.label "Zipcode" %>
    <%= f.text_field :zipcode %><br />
<%= f.label "Email" %>
<%= f.text_field :email %><br />
<%= f.label "Electric Company" %>
<%= f.text_field :electric %><br />
<%= f.label "Gas Company" %>
<%= f.text_field :nat_gas %><br />
<%= f.label 'Enter "LPG" if you use propane' %>
<%= f.text_field :propane %><br />
<%= f.label "Alternative Energy/Heating Source? (YES/NO)" %>
<%= f.text_field :alt_heat_fuel %>


 
<br />
<%= f.submit "Submit" %>


<% end %>

app/views/customers/show.html.erb
<% render customer %>

app/views/home/show.html.erb
<h1>Welcome to the Energy Use and Cost App!</h1>
<br />
<%= link_to "Sign Up", new_customer_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DOE</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>